/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/grit.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Text004.geometry} material={materials['Material.003']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Text005.geometry} material={materials['Material.004']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Text006.geometry} material={materials['Material.005']} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/grit.glb')
